CREATE OR REPLACE STREAM LANDING_GAMES_STREAM ON TABLE FOOTBALL_UCL.LANDING.GAMES
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM LANDING_GAME_EVENTS_STREAM ON TABLE FOOTBALL_UCL.LANDING.GAME_EVENTS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM LANDING_PLAYERS_STREAM ON TABLE FOOTBALL_UCL.LANDING.PLAYERS
APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK MERGE_STAGE_PLAYERS
WAREHOUSE = 'COMPUTE_WH'
SCHEDULE = '1 minute' 
WHEN system$stream_has_data('FOOTBALL_UCL.STAGING.STAGE_PLAYERS') AS
MERGE INTO FOOTBALL_UCL.TARGET.TGT_PLAYERS TGT
USING FOOTBALL_UCL.STAGING.STAGE_PLAYERS SRC ON
SRC.PLAYER_ID = TGT.PLAYER_ID  AND
SRC.FULL_NAME = TGT.FULL_NAME AND
SRC.DATE_OF_BIRTH = TGT.DATE_OF_BIRTH AND
SRC.CURRENT_CLUB_ID = TGT.CURRENT_CLUB_ID AND
SRC.PLAYER_CODE= TGT.PLAYER_CODE AND
SRC.COUNTRY_OF_CITIZENSHIP =  TGT.COUNTRY_OF_CITIZENSHIP AND
SRC.POSITION = TGT.POSITION AND
SRC.IS_ACTIVE = TGT.IS_ACTIVE AND
SRC.AGE_CATEGORY = TGT.AGE_CATEGORY AND
SRC.CURRENT_CLUB_NAME = TGT.CURRENT_CLUB_NAME AND
SRC.HIGHEST_MARKET_VALUE_IN_EUR = TGT.HIGHEST_MARKET_VALUE_IN_EUR
WHEN MATCHED THEN
UPDATE SET 
TGT.PLAYER_ID =SRC.PLAYER_ID ,
TGT.FULL_NAME = SRC.FULL_NAME ,
TGT.DATE_OF_BIRTH = SRC.DATE_OF_BIRTH ,
TGT.CURRENT_CLUB_ID =SRC.CURRENT_CLUB_ID ,
TGT.PLAYER_CODE =SRC.PLAYER_CODE ,
TGT.COUNTRY_OF_CITIZENSHIP =SRC.COUNTRY_OF_CITIZENSHIP ,
TGT.PLAYER_CODE= SRC.PLAYER_CODE ,
TGT.COUNTRY_OF_CITIZENSHIP =  SRC.COUNTRY_OF_CITIZENSHIP ,
TGT.POSITION = SRC.POSITION ,
TGT.IS_ACTIVE = SRC.IS_ACTIVE ,
TGT.AGE_CATEGORY = SRC.AGE_CATEGORY ,
TGT.CURRENT_CLUB_NAME = SRC.CURRENT_CLUB_NAME ,
TGT.HIGHEST_MARKET_VALUE_IN_EUR = SRC.HIGHEST_MARKET_VALUE_IN_EUR,
TGT.REC_INS_TS = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (
        PLAYER_GAME_KEY,
        PLAYER_ID,
        FULL_NAME,
        DATE_OF_BIRTH,
        CURRENT_CLUB_ID,
        PLAYER_CODE,
        COUNTRY_OF_CITIZENSHIP,
        POSITION,
        IS_ACTIVE,
        AGE_CATEGORY,
        CURRENT_CLUB_NAME,
        HIGHEST_MARKET_VALUE_IN_EUR,
        USER_ID,
        REC_INS_TS
    ) VALUES (
        src.PLAYER_GAME_KEY,
        src.PLAYER_ID,
        src.FULL_NAME,
        src.DATE_OF_BIRTH,
        src.CURRENT_CLUB_ID,
        src.PLAYER_CODE,
        src.COUNTRY_OF_CITIZENSHIP,
        src.POSITION,
        src.IS_ACTIVE,
        src.AGE_CATEGORY,
        src.CURRENT_CLUB_NAME,
        src.HIGHEST_MARKET_VALUE_IN_EUR,
        'STAGE_PLAYERS',
        CURRENT_TIMESTAMP
    );
