CREATE OR REPLACE STREAM LANDING_GAMES_STREAM ON TABLE FOOTBALL_UCL.LANDING.GAMES
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM LANDING_GAME_EVENTS_STREAM ON TABLE FOOTBALL_UCL.LANDING.GAME_EVENTS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM LANDING_PLAYERS_STREAM ON TABLE FOOTBALL_UCL.LANDING.PLAYERS
APPEND_ONLY = TRUE;
