CREATE OR REPLACE  TABLE TGT_PLAYERS (
    PLAYER_GAME_KEY INT AUTOINCREMENT ,
    PLAYER_ID INT,
    FULL_NAME VARCHAR(60),
    DATE_OF_BIRTH DATE,
    CURRENT_CLUB_ID INT,
    PLAYER_CODE VARCHAR(60),
    COUNTRY_OF_CITIZENSHIP VARCHAR(40),
    POSITION VARCHAR(15),
    IS_ACTIVE BOOLEAN,
    AGE_CATEGORY VARCHAR(25),
    CURRENT_CLUB_NAME TEXT,
    HIGHEST_MARKET_VALUE_IN_EUR INT,
    USER_ID VARCHAR(15),
    REC_INS_TS TIMESTAMP
);

SHOW COLUMNS IN TABLE TGT_PLAYERS;

INSERT INTO TGT_PLAYERS(
PLAYER_GAME_KEY
,PLAYER_ID
,FULL_NAME
,DATE_OF_BIRTH
,CURRENT_CLUB_ID
,PLAYER_CODE
,COUNTRY_OF_CITIZENSHIP
,POSITION
,IS_ACTIVE
,AGE_CATEGORY
,CURRENT_CLUB_NAME
,HIGHEST_MARKET_VALUE_IN_EUR
,USER_ID
,REC_INS_TS)
SELECT 
ROW_NUMBER() OVER(ORDER BY PLAYER_ID),
PLAYER_ID
,FULL_NAME
,DATE_OF_BIRTH
,CURRENT_CLUB_ID
,PLAYER_CODE
,COUNTRY_OF_CITIZENSHIP
,POSITION
,IS_ACTIVE
,AGE_CATEGORY
,CURRENT_CLUB_NAME
,HIGHEST_MARKET_VALUE_IN_EUR
,'STAGE_PLAYERS'
,CURRENT_TIMESTAMP
FROM STAGING.STAGE_PLAYERS;


SELECT COUNT(*) FROM TARGET.TGT_PLAYERS;
